apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: intelligent-mall-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: intelligent-mall-runtime
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: intelligent-mall/runtime
        property: database_url
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: intelligent-mall/runtime
        property: jwt_secret_key
